-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR FROM ICECREAM_INFO, FIRST_HALF 
WHERE ICECREAM_INFO.FLAVOR =  FIRST_HALF.FLAVOR
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' 
AND FIRST_HALF.TOTAL_ORDER > 3000;

